SELECT * FROM ALL_TIME_OUTDOOR_TOP_LIST
SELECT * FROM SEASON_OUTDOOR_TOP_LIST

-- 1.
SELECT RESULT, NAME, DENSE_RANK() OVER(ORDER BY RESULT)
FROM ALL_TIME_OUTDOOR_TOP_LIST

-- 2.
SELECT RESULT, NAME, LAG(CAST(result AS DECIMAL(18, 2)), 0, 0.00) OVER (ORDER BY result) - (SELECT MIN(RESULT) FROM ALL_TIME_OUTDOOR_TOP_LIST) AS DIFF
FROM ALL_TIME_OUTDOOR_TOP_LIST

-- 3.
SELECT RESULT, NAME, CAST(result AS DECIMAL(18, 2)) - LAG(CAST(result AS DECIMAL(18, 2)), 1, NULL) OVER (ORDER BY result) AS DIFF
FROM ALL_TIME_OUTDOOR_TOP_LIST