-- 1.
SELECT name
FROM ALL_TIME_OUTDOOR_TOP_LIST
UNION
SELECT name
FROM SEASON_OUTDOOR_TOP_LIST

-- 2.
SELECT name
FROM ALL_TIME_OUTDOOR_TOP_LIST
EXCEPT
SELECT name
FROM SEASON_OUTDOOR_TOP_LIST

-- 3.
SELECT name
FROM SEASON_OUTDOOR_TOP_LIST
INTERSECT
SELECT name
FROM ALL_TIME_OUTDOOR_TOP_LIST

-- 4.
    (SELECT name
FROM SEASON_OUTDOOR_TOP_LIST
UNION
SELECT name
FROM ALL_TIME_OUTDOOR_TOP_LIST)
EXCEPT
(SELECT name
 FROM SEASON_OUTDOOR_TOP_LIST
 INTERSECT
 SELECT name
 FROM ALL_TIME_OUTDOOR_TOP_LIST)


